# Generated by Django 6.0.2 on 2026-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_picture',
            field=models.ImageField(blank=True, null=True, upload_to='passport_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
