# Generated by Django 6.0.2 on 2026-02-25 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_rename_gender_profile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='managed_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_Profile_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('managed_Profile_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('managed_Profile_date_of_birth', models.DateField(blank=True, null=True)),
                ('managed_Profile_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('managed_Profile_country_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('managed_Profile_city_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('managed_Profile_passport_picture', models.ImageField(blank=True, null=True, upload_to='passport_pictures/')),
                ('managed_Profile_passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('managed_Profile_profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
