# Generated by Django 6.0.2 on 2026-02-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='can_manage_content',
            field=models.BooleanField(default=False),
        ),
    ]
