# Generated by Django 6.0.2 on 2026-03-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminprofile_can_manage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_group',
            field=models.BooleanField(default=False),
        ),
    ]
