# Generated by Django 6.0.2 on 2026-03-04 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_can_create_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
