# Generated by Django 6.0.2 on 2026-03-04 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_governmentform_formrequirement_categoryform_requirement_eligibility'),
        ('users', '0007_managedprofile_created_by_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=500)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(limit_choices_to={'is_eligibility': True}, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_answers', to='cases.requirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requirement__name'],
                'unique_together': {('user', 'requirement')},
            },
        ),
    ]
