# Generated by Django 6.0.2 on 2026-02-20 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('document', 'Document Upload'), ('question', 'Question'), ('text', 'Text Field'), ('number', 'Number'), ('date', 'Date')], max_length=20),
        ),
        migrations.CreateModel(
            name='CaseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_number', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='case_files/')),
                ('is_auto_filled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cases.case')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.requirement')),
            ],
        ),
    ]
