# Generated by Django 6.0.2 on 2026-02-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_requirement_type_caseanswer'),
        ('groups', '0002_grouppermission_alter_group_options_and_more'),
        ('users', '0004_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='groups.group'),
        ),
        migrations.AddField(
            model_name='case',
            name='managed_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='users.managedprofile'),
        ),
    ]
