# Generated by Django 6.0.2 on 2026-02-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_group_case_managed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_extra', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_requirements', to='cases.case')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.requirement')),
            ],
            options={
                'unique_together': {('case', 'requirement')},
            },
        ),
    ]
