# Generated by Django 6.0.2 on 2026-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_caserequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseanswer',
            name='edited_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseanswer',
            name='notify_user',
            field=models.BooleanField(default=False),
        ),
    ]
