# Generated by Django 6.0.2 on 2026-03-02 21:15
# Modified to handle existing rows:
#   Step 1 — Add slug as nullable (no unique yet)
#   Step 2 — Data migration: populate slugs for existing rows
#   Step 3 — Make slug non-nullable + unique

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Auto-fill slug for any Category or Service that doesn't have one yet."""
    Category = apps.get_model('cases', 'Category')
    Service  = apps.get_model('cases', 'Service')

    for model_cls in (Service, Category):
        for obj in model_cls.objects.all():
            if not obj.slug:
                base    = slugify(obj.name)[:100] or f'item-{obj.pk}'
                slug    = base
                counter = 2
                while model_cls.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
                    slug = f'{base}-{counter}'
                    counter += 1
                obj.slug = slug
                obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_caseanswer_edited_by_admin_caseanswer_notify_user'),
    ]

    operations = [
        # Step 1 — add fields as nullable, no unique constraint yet
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),

        # Step 2 — fill in slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),

        # Step 3 — tighten to unique=True, null=False
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
