# Generated by Django 6.0.2 on 2026-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_alter_categoryrequirement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='form_field_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
