# Generated by Django 6.0.2 on 2026-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_requirement_form_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='managed_profile_mapping',
            field=models.CharField(blank=True, help_text="Dot-path into ManagedProfile for auto-fill when filling on behalf of an interior person. E.g. 'first_name', 'date_of_birth', 'passport_number'.", max_length=100, null=True),
        ),
    ]
