# Generated by Django 6.0.2 on 2026-03-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_requirement_managed_profile_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='eligibility_fail_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='eligibility_operator',
            field=models.CharField(blank=True, choices=[('on_or_before_date', 'On or before date'), ('before_date', 'Strictly before date'), ('on_or_after_date', 'On or after date'), ('after_date', 'Strictly after date'), ('equals', 'Equals'), ('not_equals', 'Does not equal'), ('contains', 'Contains text'), ('yes', 'Answer is Yes'), ('no', 'Answer is No')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='eligibility_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_eligibility',
            field=models.BooleanField(default=False, help_text="Mark as eligibility gate: the user's answer is checked against a condition. Fails block the application."),
        ),
        migrations.CreateModel(
            name='FormRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_section', models.CharField(blank=True, max_length=100)),
                ('field_id', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_requirements', to='cases.requirement')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_requirements', to='cases.governmentform')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='CategoryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_forms', to='cases.category')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_forms', to='cases.governmentform')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'form')},
            },
        ),
    ]
