# Generated by Django 6.0.2 on 2026-03-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_governmentform_formrequirement_categoryform_requirement_eligibility'),
        ('users', '0008_eligibilityanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically each time the crawler successfully processes this category.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='source_url',
            field=models.URLField(blank=True, help_text='Government page describing this program. Used by the crawler to auto-populate requirements and forms.', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CrawlerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('requirement', 'Requirement / Question'), ('eligibility', 'Eligibility Condition'), ('form', 'Government Form (PDF)')], default='requirement', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('raw_text', models.TextField(help_text='Raw text extracted from the source page or PDF before NLP processing.')),
                ('suggested_name', models.CharField(blank=True, help_text='NLP-suggested requirement name (admin can edit before accepting).', max_length=255)),
                ('suggested_type', models.CharField(blank=True, help_text='NLP-suggested type: text, date, boolean, select, file, info_text.', max_length=20)),
                ('suggested_url', models.URLField(blank=True, help_text='URL of the discovered PDF or form page.', max_length=500)),
                ('match_confidence', models.FloatField(default=0.0, help_text='NLP match confidence: 0.0 = no match, 1.0 = certain match.')),
                ('eligibility_operator', models.CharField(blank=True, help_text='NLP-parsed operator: gte, lte, eq, etc. May be empty if parsing failed.', max_length=30)),
                ('eligibility_value', models.CharField(blank=True, help_text='NLP-parsed threshold value. May be empty if parsing failed.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='The category whose source_url was crawled to produce this suggestion.', on_delete=django.db.models.deletion.CASCADE, related_name='crawler_suggestions', to='cases.category')),
                ('created_requirement', models.ForeignKey(blank=True, help_text='Requirement that was created when this suggestion was accepted. Null = not accepted or linked existing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_suggestion', to='cases.requirement')),
                ('matched_requirement', models.ForeignKey(blank=True, help_text='Best-matching existing Requirement found by NLP. Null = no match found.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_suggestions', to='cases.requirement')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who accepted or rejected this suggestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to='users.adminprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
