# Generated by Django 6.0.2 on 2026-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_category_crawler_fields_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentform',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='government_forms/'),
        ),
    ]
