# Generated by Django 6.0.2 on 2026-03-02 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('body', models.TextField()),
                ('meta_description', models.CharField(blank=True, help_text='Shown in Google search results. Keep under 160 characters.', max_length=160)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='CaseFlow', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Professional Immigration Services', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=200)),
                ('instagram_url', models.CharField(blank=True, max_length=200)),
                ('hero_title', models.CharField(default='Immigration Made Simple', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Expert guidance every step of the way. From visa applications to permanent residency, we handle the complexity so you can focus on your future.')),
                ('hero_cta_text', models.CharField(default='Get Started', max_length=60)),
                ('about_title', models.CharField(default='About Us', max_length=200)),
                ('about_body', models.TextField(blank=True, default='We are a team of dedicated immigration professionals committed to helping individuals and families navigate the immigration process with confidence.')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
