# Generated by Django 6.0.2 on 2026-03-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_accent_light',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_background',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='color_primary',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
