# Generated by Django 6.0.2 on 2026-02-26 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['group_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='can_fill_cases',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='can_manage_members',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='can_view_members',
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='groups.grouppermission'),
        ),
    ]
